# Generated by Django 4.2 on 2023-04-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Replication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('transfer_time', models.DateTimeField(auto_now_add=True)),
                ('transfer_duration', models.IntegerField()),
                ('dest_vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replications_received', to='file_uploader.vps')),
                ('source_vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replications_sent', to='file_uploader.vps')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('upload_duration', models.FloatField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('source_vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='file_uploader.vps')),
            ],
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_duration', models.FloatField()),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_downloaded', to='file_uploader.fileupload')),
                ('source_vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_downloaded', to='file_uploader.vps')),
            ],
        ),
    ]
