# Generated by Django 4.2 on 2023-04-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedownload',
            old_name='download_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='upload_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='transfer_time',
            new_name='created_at',
        ),
    ]
