# Generated by Django 4.2 on 2023-04-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0003_alter_fileupload_link_alter_replication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replication',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replications', to='file_uploader.fileupload'),
        ),
    ]
