version: '3.7'

services:

  postgres:
    image: postgres:14.5
    container_name: upload_project_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=upload_projectFr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    platform: linux/amd64
    build: .
    container_name: upload_project_container
    env_file:
      - ./set_env.sh
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --database=$${EUROPE_DB_HOST} &&
             python manage.py populate_vps_model &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/upload_project
      - ~/.ssh:/root/.ssh
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    expose:
      - 6379

  celery:
      restart: always
      build:
        context: .
      command: celery -A upload_project worker -l info
      volumes:
        - .:/upload_project
        - ~/.ssh:/root/.ssh
      env_file:
        - ./set_env.sh
      depends_on:
        - postgres
        - redis
        - web

volumes:
  pgdata:
